### ISSUE TITLE
Run phpstan in CI

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-security#100]
Would it be possible to run it also?

**Comment by chesio** [comment]
Hi @szepeviktor, PHPStan is already being run in CI, see: https://github.com/chesio/bc-security/runs/614637113?check_suite_focus=true#step:6:5

The CI test suite runs phpcs, phpstan and phpunit tests. I only omitted integration tests, because they require full WordPress installation.

**Comment by szepeviktor** [comment]
I see.

`composer run-script ci`
