### ISSUE TITLE
Switch from WP_ENV to WP_ENVIRONMENT_TYPE

### ISSUE THREAD

**Issue by chesio** [chesio/bc-security#102]
See: https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/

Notes:
* If support for `WP_ENV` is dropped, it is a breaking change.
* WordPress 5.5 is required.

**Comment by szepeviktor** [comment]
@chesio What a harmful decision from WordPress makers!
Half the world usdes `WP_ENV`.

**Comment by chesio** [comment]
@szepeviktor Yeah, I was surprised too that they picked a different name...
