### ISSUE TITLE
Support PHP 8.0

### ISSUE THREAD

**Issue by chesio** [chesio/bc-security#104]
To be released at the end of November 2020.

**Comment by szepeviktor** [comment]
PHP 7.2 should be dropped or we have to use two versions of PHPUnit.

**Comment by chesio** [comment]
The plan is to drop PHP 7.2, but since there are some integration tests that depend on WordPress test suite, I have to make sure they work with given version of PHPUnit.

Perhaps related: https://core.trac.wordpress.org/ticket/46149

**Comment by szepeviktor** [comment]
Try migrating to WorDBless by Automattic (and me) https://github.com/Automattic/wordbless

**Comment by chesio** [comment]
Thanks for the tip, looks interesting!
