### ISSUE TITLE
Feedback.

### ISSUE THREAD

**Issue by paaljoachim** [chesio/bc-security#113]
Hey

I am doing research into various WordPress Security plugins. It seems that various plugins of course have their advantages and disadvantages. I have been using All in One WP Security & Firewall plugin, and noticed your readme comment.

> "All In One WP Security & Firewall - another very popular security plugin for WordPress. I have used AIOWPSF for quite some time; it has a lot of features, but also lot of small bugs (sometimes not that small). I used to contribute to the plugin, but the codebase is rather messy and after some time I got tired struggling with it."

Based on posting feature suggestions to their WP support forum: https://wordpress.org/support/plugin/all-in-one-wp-security-and-firewall/ I have a feeling that it is not being followed up as closely by the developers as it should.
I also noticed the PR's on their Github repo are really old and not followed up.

I downloaded the BC Security plugin from the Github repo easiest method for me, and went through each BC Security sub page. It feels nice and tight.

I assume you will continue to pick up some features from here and there that have been added to other Security plugins and add a modified version into the BC Security plugin.

**Comment by chesio** [comment]
Hi @paaljoachim,

thanks for your feedback!

That comment about All In One WP Security & FIrewall plugin is several years old already, but based on your experience it still seems valid.

> I downloaded the BC Security plugin from the Github repo easiest method for me [...]

In such case I recommend to use [Git Updater](https://github.com/afragen/git-updater) to keep the plugin updated. But the updates are not that frequent, so if you are only testing it, updating manually should be feasible.

> I assume you will continue to pick up some features from here and there that have been added to other Security plugins and add a modified version into the BC Security plugin.

I probably will, although I want to keep the plugin simple, so it never be as feature-packed as other security plugins. I mainly keep an eye on what Wordfence adds to their plugin and implement features that I find relevant for my projects.

Anyway, I'm always open to feedback and feature suggestions, so feel free to open an issue if you have any!

**Comment by paaljoachim** [comment]
Hey there are plans for a premium version of the All in One Security plugin. I received a response on the support forum at the plugin repo. I also made an issue on their Github repo which hopefully in a while will be responded to: https://github.com/Arsenal21/all-in-one-wordpress-security/issues/121

**Comment by chesio** [comment]
Hi, thanks for letting me know.

I don't follow the development of All in One WordPress Security plugin anymore, mainly because of lack of any feedback on GitHub. I would certainly appreciate if they changed their attitude - if pro version is going to help with that then I wish them good luck with it.

**Comment by DavidAnderson684** [comment]
AIOS does not have a Github - the account you're looking at there is the personal Github account of a previous owner, which is why the last code commit there was in 2021.
