### ISSUE TITLE
oEmbed needs REST API 

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-security#74]
If we enable only authenticated REST API we should disable oEmbeds.
What do you think?

```html
<link rel="alternate" type="application/json+oembed" href="https://www.atlantischild.hu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.atlantischild.hu%2F" />
<link rel="alternate" type="text/xml+oembed" href="https://www.atlantischild.hu/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.atlantischild.hu%2F&#038;format=xml" />
```

**Comment by chesio** [comment]
Hi Viktor,

Thanks for pointing that out! I agree it makes no sense to output links to oEmbeds when they are not going to work. I'm going to fix that.

**Comment by szepeviktor** [comment]
REST API is wildly used across many plugins.
Yoast SEO, Contact Form 7 etc.

**Comment by chesio** [comment]
I know. Personally I don't disable it anymore. I used to do it in the transition period, when it was new and untested (and [insecure](https://blog.sucuri.net/2017/02/content-injection-vulnerability-wordpress-rest-api.html)). I think now it has matured enough.

So maybe it's time to remove this feature instead?

**Comment by szepeviktor** [comment]
In my WAF only `/wp/v2/users*` is disabled

https://github.com/szepeviktor/wordpress-fail2ban/blob/master/mu-plugin/wp-fail2ban-mu-instant.php#L407-L418

**Comment by chesio** [comment]
Makes sense. Thanks for feedback!

**Comment by szepeviktor** [comment]
BTW: `rest_cannot_access`

WP REST API sets `wp_set_current_user( 0 );` if you are logged in and do not have a nonce for the REST request.

**Comment by chesio** [comment]
Hi Victor,

just a follow up: I ended up replacing the "Disable access to REST API to anonymous users" feature with "Prevent usernames discovery" feature: it includes both disabling anonymous access to `wp/v2/users` REST API endpoint and blocking of usernames enumeration.

Btw. I basically ripped off the implementation of this feature from Wordfence (with some minor modifications - their codebase is not that clean).

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@chesio You do normal programming which leaves the website open for

- vulnerability probes
- D/DoS attacks

my WAF [acts immediately](https://github.com/szepeviktor/wordpress-fail2ban/blob/master/core-events/waf4wordpress-core-events.php#L410-L421), trigger_instant() writes a special string to the PHP errorlog which is watched by Fail2ban who triggers the firewall and bans the _user lister_ IP for 24 hours.

**Comment by szepeviktor** [comment]
@chesio Embed API is under attack!

```
/wp-json/oembed/1.0/embed?url=https://example.com/path/&pdPI=8861 AND 1=1 UNION ALL SELECT 1,NULL,'<script>alert("XSS")</script>',table_name FROM information_schema.tables WHERE 2>1--/**/; EXEC xp_cmdshell('cat ../../../etc/passwd')#
/wp-json/oembed/1.0/embed?url=https://example.com/path/.',,)).,,"
/wp-json/oembed/1.0/embed?url=https://example.com/path/'PRtfbL<'">YZbJTl
/wp-json/oembed/1.0/embed?url=https://example.com/path/) AND 4961=5298 AND (2667=2667
/wp-json/oembed/1.0/embed?url=https://example.com/path/) AND 2397=2397 AND (2357=2357
/wp-json/oembed/1.0/embed?url=https://example.com/path/ AND 5375=1932
/wp-json/oembed/1.0/embed?url=https://example.com/path/ AND 2397=2397
/wp-json/oembed/1.0/embed?url=https://example.com/path/') AND 3822=3732 AND ('BxhJ'='BxhJ
/wp-json/oembed/1.0/embed?url=https://example.com/path/') AND 2397=2397 AND ('rNhB'='rNhB
/wp-json/oembed/1.0/embed?url=https://example.com/path/' AND 7437=4236 AND 'KxZD'='KxZD
```
