### ISSUE TITLE
Relax ABSPATH check in scanDirectoryForUnknownFiles() helper function

### ISSUE THREAD

**Issue by chesio** [chesio/bc-security#80]
Now this functions triggers "doing it wrong" notice when the directory to check is not (under) `ABSPATH`, but there are setups (Bedrock for example) that have plugins in another directory than WordPress core.

**Comment by szepeviktor** [comment]
Any decent WP install puts core files in a subdirectory, thus there will be barely anything under `ABSPATH`.

[An overview on this](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wordpress/class-siteinfo.php#L20-L47)
