### ISSUE TITLE
Prevent new registrations with usernames on blacklist

### ISSUE THREAD

**Issue by chesio** [chesio/bc-security#81]
Should be simple to implement:
1. Update UI to make it clear that blacklisted usernames are prevented from registration as well.
2. Pass the existing blacklist to the [`illegal_user_logins`](https://developer.wordpress.org/reference/hooks/illegal_user_logins/) filter.

**Comment by szepeviktor** [comment]
@chesio Gathered from botnet attacks: https://github.com/szepeviktor/waf4wordpress/blob/master/http-analyzer/waf4wordpress-http-analyzer.php#L59-L95

**Comment by chesio** [comment]
@szepeviktor I start to believe you are a bot yourself, such a quick comment ;-) Thanks for the list, I'll let myself inspire :-)

**Comment by szepeviktor** [comment]
🤖

**Comment by szepeviktor** [comment]
I was not aware of the filter above. Thank you!
My WAF needs to act (ban) on first unusual probe, so a filter may not be effective in this case.
