### ISSUE TITLE
Blog name is HTML-escaped in email subject

### ISSUE THREAD

**Issue by chesio** [chesio/bc-security#86]
The problem is that blog name is stored HTML-escaped in database, so it must be unescaped before it is passed to wp_mail(). What a mess...

See also: https://core.trac.wordpress.org/ticket/25346

**Comment by szepeviktor** [comment]
Only 6 years old. What a bright future!

**Comment by chesio** [comment]
Well, this one has been resolved swiftly, but instead of fixing the problem itself (HTML-encoded content in database), WordPress devs decided to workaround it, so the problem bites [again](https://core.trac.wordpress.org/ticket/35283) and [again](https://core.trac.wordpress.org/ticket/40015) ...

**Comment by szepeviktor** [comment]
I've heard on WP SLack: WordPress is an undecipherable mess.

**Comment by chesio** [comment]
> I've heard on WP SLack: WordPress is an undecipherable mess.

I agree. The move to raise minimum required PHP version after years of inaction gave me some hope, but there's still long way to go. And such legacy issues like this one, that are not properly addressed because of backwards compatibility, can be a real PITA.
