### ISSUE TITLE
Introduce CI

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-security#90]
- GitHub Actions?
- Travis?
- CircleCI?

I would help implementing it.

**Comment by chesio** [comment]
I have no experience with any of them, so recommendations are welcome. I just noticed that Travis has been getting negative press recently and some projects are moving from it to CircleCI.

Btw. until now I haven't bothered myself with pull requests (as you may have noticed) and I just directly push to develop branch - how would that work with CI?

**Comment by szepeviktor** [comment]
> how would that work with CI?

CI tests both but not able to stop direct pushes.

AFAIK None of them are highly reliable.

Use a 🎲 and divide the result by two to choose a CI!

**Comment by szepeviktor** [comment]
I would gladly learn GitHub Actions by creating a Docker image.

**Comment by chesio** [comment]
Any PRs are welcome :-)

**Comment by chesio** [comment]
@szepeviktor I decided for GitHub Actions as that was most straight-forward. I used Ubuntu image instead Debian, it's been the default option and I don't think it makes any difference in this case. If you have any ideas how to improve workflow file, feel free to open a PR!

Thanks for the suggestion!
