### ISSUE TITLE
Include installation instructions

### ISSUE THREAD

**Issue by szepeviktor** [chesio/bc-security#93]
Please add a new section to README.

**Comment by szepeviktor** [comment]
❤️

**Comment by szepeviktor** [comment]
Will you register it on Packagist? https://packagist.org/packages/chesio/bc-security

**Comment by chesio** [comment]
> Will you register it on Packagist? https://packagist.org/packages/chesio/bc-security

I'll do. It's been almost 3 years since I released the first version of the plugin and I still use it, so I guess it proved to be useful enough.
